---
title: "Untitled"
author: "Naman Dhameja"
date: "20/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
#install.packages('compare')
library(compare)
library(stringr)
```
Import Data
```{r}
library(readxl)
data <- read_excel("C:/Users/gupta/Documents/GitHub/data3_DataWrangling/India Credit Data.xlsx", skip = 1)
View(data)
# Remove first row
data<-data[-1,]
```
Removing Using length logic
```{r}
data$`BORROWER ID`[1]
nchar(data$`BORROWER ID`[1])
nchar(data$`BORROWER ID`[98])
# ct<-0
# for(i in 1:range(nrow(data))){
#   if(nchar(data$`BORROWER ID`[i])>=18){
#     print(data$`BORROWER ID`[i])
#     
#     data<-data[-c(i),]
#   }
# }
## _____--------______##
for(i in 1:range(nrow(data))){
  if(nchar(data$`BORROWER ID`[i])>=18){
    print(data$`BORROWER ID`[i])
    
    data<-data[-c(i),]
  }
}
# 2nd method
for(i in 1:range(nrow(data))){
  text = data$`BORROWER ID`[i]
   if(str_count(text, ' ')>0){
     data<-data[-c(i),]
   }
}

```
\\
Remove columns with "End of..."
```{r}
# 3rd method
data<-data[-c(98,197,298,398,498,1006),]
View(data)
```

Converting different formats of string to one.

```{r}
unique(data$`Bank Account`)
tolower(unique( data$`Bank Account`))
trial<-data$`Bank Account`
trial<-str_replace_all(tolower(data$`Bank Account`),"-","")
unique(trial)

data$`Bank Account`<-str_replace_all(tolower(data$`Bank Account`),"-","")
data$`Bank Account`<-replace(data$`Bank Account`,data$`Bank Account`=="dnk","do not know")

data$`Bank Account`<-replace(data$`Bank Account`,data$`Bank Account`=="nba","no bank account")
unique(data$`Bank Account`)
View(data)
```

Gender column to M,F,O only
```{r}
data$Gender<-str_replace_all(tolower(data$Gender),"-","")

unique(data$Gender)
data$Gender<-replace(data$Gender,data$Gender=="male","M")
data$Gender<-replace(data$Gender,data$Gender=="m","M")

data$Gender<-replace(data$Gender,data$Gender=="female","F")
data$Gender<-replace(data$Gender,data$Gender=="f","F")

data$Gender<-replace(data$Gender,data$Gender=="other","O")
data$Gender<-replace(data$Gender,data$Gender=="o","O")

unique(data$Gender)

View(data)
```


Converting multiple NAs to "Missing"
```{r}
data$`Bank Account`[which(is.na(data$`Bank Account`))]="Missing"
data$Purpose[which(is.na(data$Purpose))]="Missing"
data$`Marital status`[which(is.na(data$`Marital status`))]="Missing"
data$SECURITY[which(is.na(data$SECURITY))]="Missing"
data$Occupation[which(is.na(data$Occupation))]="Missing"

```

Replace '-' characters in Months column
```{r}
data$Months <- str_replace_all(as.character(data$Months),"-","")
data$Age<-as.numeric(data$Age)
data$Months<-as.numeric(data$Months)

View(data)
```


Loan Closed column into Y,N only
```{r}
unique(data$`Loan Closed`)
data$`Loan Closed`<-replace(data$`Loan Closed`,data$`Loan Closed`=="No","N")
data$`Loan Closed`<-replace(data$`Loan Closed`,data$`Loan Closed`=="NO","N")
data$`Loan Closed`<-replace(data$`Loan Closed`,data$`Loan Closed`=="n","N")
data$`Loan Closed`<-replace(data$`Loan Closed`,data$`Loan Closed`=="N","N")

data$`Loan Closed`<-replace(data$`Loan Closed`,data$`Loan Closed`=="y","Y")
data$`Loan Closed`<-replace(data$`Loan Closed`,data$`Loan Closed`=="YES","Y")

data$`Loan Closed`<-replace(data$`Loan Closed`,data$`Loan Closed`=="Y","Yes")
data$`Loan Closed`<-replace(data$`Loan Closed`,data$`Loan Closed`=="N","No")

unique(data$`Loan Closed`)


```

```{r}

unique(data$Purpose)
head(data$`Loan Amount`,10)
head(data$`Annual Income`,10)
data$`Annual Income`<-as.integer(data$`Annual Income`)
```

```{r}
unique(data$`Marital status`)
data$`Marital status`<-tolower(data$`Marital status`)
unique(data$`Marital status`)

```

```{r}
unique(data$SECURITY)

```

```{r}
trial<-c()
#`%nin%`<-Negate(`%in%`)
unique(data$Purpose)
other<-list("missing","others")
good<-list("education","business","farming")
bad<-list("household furniture/equipment","vehicle purchase  (used)","vacation" ,"domestic appliances","vehicle purchase (new)","work furniture/equipment","television","repairs" )
for( i in 1:range(nrow(data))){
  if(data$Purpose[i] %in% bad ){
    #append(trial,data$Purpose[i])
    trial<-c(trial,"Bad Loan")
    
  }else if(data$Purpose[i] %in% good){
    trial<-c(trial,"Good Loan")
  }else{
    trial<-c(trial,"Missing/Other")
  }
}
data$LoanType<-trial
View(data)
summary(as.factor(data$LoanType))
```
```{r}

for( i in 1:range(nrow(data))){
  if(data$`# paid`[i]==48){
    data$`Loan Closed`[i]<-"Yes"
  }
  }


```
```{r}
View(data)
for( i in 1:range(nrow(data))){
  data$`% Paid`[i]<-round((data$`# paid`[i]/48)*100,2)
  }

```
Potential Defaulter
```{r}
trial<-c()

for( i in 1:range(nrow(data))){
  if(data$`% Paid`[i]<=40 && data$`# skipped`[i]>=round(data$`# paid`[i]*0.3,0) ){
    trial<-c(trial,"Yes")
    
  }else{
    trial<-c(trial,"No")
  }
}
data$PotentialDefaulter<-trial
View(data)
summary(as.factor(data$PotentialDefaulter))

library(ggplot2)

#potential defaulters and loan amount and purpose
ggplot(data) +
 aes(x = PotentialDefaulter, y = `Loan Amount`, fill = Purpose) +
 geom_boxplot(shape = "circle") +
 scale_fill_hue(direction = 1) +
 theme_minimal()
#potential defaulters and loan amount and purpose grouped by gender
ggplot(data) +
 aes(x = PotentialDefaulter, y = `Loan Amount`, fill = Purpose) +
 geom_boxplot(shape = "circle") +
 scale_fill_hue(direction = 1) +
 theme_minimal() +
 facet_wrap(vars(Gender))


library(dplyr)
library(ggplot2)
#potential defaulters and loan amount based on marital status
data %>%
 filter(!(`Marital status` %in% "missing")) %>%
 ggplot() +
 aes(x = PotentialDefaulter, y = `Loan Amount`, fill = `Marital status`) +
 geom_boxplot(shape = "circle") +
 scale_fill_hue(direction = 1) +
 theme_minimal()
#loan type based on loan closed or not
data %>%
 filter(!(`Marital status` %in% "missing")) %>%
 filter(!is.na(`Loan Closed`)) %>%
 filter(!(LoanType %in% 
 "Missing/Other")) %>%
 ggplot() +
 aes(x = LoanType, y = `Loan Amount`, fill = `Loan Closed`) +
 geom_boxplot(shape = "circle") +
 scale_fill_hue(direction = 1) +
 theme_minimal()


```


